// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUYuH2xhagBQ-G31k7BHHYTysf8aAjFKE',
    appId: '1:97750412702:web:0d5508ce5dbb9fbea67a8f',
    messagingSenderId: '97750412702',
    projectId: 'budget-app-9681f',
    authDomain: 'budget-app-9681f.firebaseapp.com',
    storageBucket: 'budget-app-9681f.firebasestorage.app',
    measurementId: 'G-RT2CDZ2VB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuHLKpl0RHZHKbzHkPzT9Ee537bimK0xA',
    appId: '1:97750412702:android:af1a488d4a77c3eda67a8f',
    messagingSenderId: '97750412702',
    projectId: 'budget-app-9681f',
    storageBucket: 'budget-app-9681f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLd_R9clGeeyKOtviBDDuIRMwlrejaNfI',
    appId: '1:97750412702:ios:3a59f1ac79a4f5b1a67a8f',
    messagingSenderId: '97750412702',
    projectId: 'budget-app-9681f',
    storageBucket: 'budget-app-9681f.firebasestorage.app',
    androidClientId: '97750412702-pqm85sgoor571eseq4t6etj5o0kv55g8.apps.googleusercontent.com',
    iosClientId: '97750412702-8alkv624ef41f0tqih7b5rhbme0m2fkc.apps.googleusercontent.com',
    iosBundleId: 'com.codingliquids.budgetAppStarting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUYuH2xhagBQ-G31k7BHHYTysf8aAjFKE',
    appId: '1:97750412702:web:b81b96f36966e064a67a8f',
    messagingSenderId: '97750412702',
    projectId: 'budget-app-9681f',
    authDomain: 'budget-app-9681f.firebaseapp.com',
    storageBucket: 'budget-app-9681f.firebasestorage.app',
    measurementId: 'G-1ZT1CWNLRY',
  );

}